
flarehopper:
    filename: "flarehopper.state"
    powerhost: "localhost"
    powerport: 5000
    energenieSocketNumber: 1

---

spring.profiles: PROD

flarehopper:
    filename: "flarehopper.state"
    powerhost: "localhost"